### PR TITLE
Add git checker

### PR DESCRIPTION
**Pull request by gasinvein**
This is similar to URL checker - it applies to all git sources and checks if the specified tag/branch is still valid.

Follow-up for #104, see also #33

### CODE REVIEW

**Comment by gasinvein** [comment]
@grulja @travier @tsdgeos  Hey there. I've seen some KDE apps on Flathub who set git tag as a branch property, like `"branch": "v1.0.0"`. Is it intentional, e.g. some convention for KDE apps?
flatpak-external-data-checker with this changes will submit PRs replacing `banch` with `tag` property (with same value). If it's not desirable - I need your advice how to handle it better.

**Comment by tsdgeos** [comment]
Can you point to some of those?

**Comment by gasinvein** [comment]
@tsdgeos Oddly enough, I can't find any such apps under org.kde. namespace anymore. Oh well, I'll then just assume that it's ok to replace branch with tag property where applicable. Sorry for bothering you.

**Comment by gasinvein** [comment]
I've removed all the guesswork. If something other than actual branch is specified in a `branch` property, the checker won't be able to retrieve remote commit and, thus, won't try to update it.

**Pull request merged**
