### PR TITLE
ci: submit coverage information to coveralls.io

### PR DESCRIPTION
**Pull request by wjt**

### CODE REVIEW

**Comment by barthalion** [comment]
Looks like there's an official GitHub action for that: https://github.com/marketplace/actions/coveralls-github-action

**Comment by wjt** [comment]
Yes, but it accepts LCOV input, and coverage.py does not produce LCOV output

**Comment by wjt** [comment]
See https://github.com/coverallsapp/github-action/issues/4 for more discussion

**Comment by wjt** [comment]
```
Submitting coverage to coveralls.io...
No source for /opt/src/__init__.py
No source for /opt/src/checker.py
No source for /opt/src/checkers/__init__.py
No source for /opt/src/checkers/debianrepochecker.py
No source for /opt/src/checkers/firefoxchecker.py
No source for /opt/src/checkers/flashchecker.py
No source for /opt/src/checkers/htmlchecker.py
No source for /opt/src/checkers/urlchecker.py
No source for /opt/src/lib/appdata.py
No source for /opt/src/lib/externaldata.py
No source for /opt/src/lib/utils.py
No source for /opt/src/main.py
No source for /opt/tests/__init__.py
No source for /opt/tests/test_appdata.py
No source for /opt/tests/test_checker.py
No source for /opt/tests/test_firefoxchecker.py
No source for /opt/tests/test_flashchecker.py
No source for /opt/tests/test_htmlchecker.py
No source for /opt/tests/test_util.py
Coverage submitted!
Job ##1.1
https://coveralls.io/jobs/56551080
```

**Pull request merged**
