### PR TITLE
ci: Tell black to output a diff

### PR DESCRIPTION
**Pull request by wjt**
As suggested on #151.

### CODE REVIEW

**Comment by wjt** [comment]
So, that works.

But maybe it would be better to make it commit the change back to the repo, à la https://github.com/psf/Black/actions/runs/17913292/workflow

**Comment by gasinvein** [comment]
> But maybe it would be better to make it commit the change back to the repo, à la https://github.com/psf/Black/actions/runs/17913292/workflow

I personally don't like auto commits, they add noise and make editing commits trickier.

**Comment by wjt** [comment]
The intention would be that the submitter would pull & squash the commit into their patch(es), saving them having to copy-paste a diff into their source tree.

**Comment by gasinvein** [comment]
Yeah, but one would need to keep that in mind and not forget to pull before adding more commits.

**Comment by wjt** [comment]
@hadess re. your comment on https://github.com/flathub/flatpak-external-data-checker/pull/151#issuecomment-790499820, would you have preferred:

a) the CI job printed a diff showing what changes you should apply; or
b) the CI job pushed a fixup commit to your branch (if it could) that you could squash?

**Comment by wjt** [comment]
Oh, well, it seems from reading https://github.com/cclauss/autoblack and https://github.community/t/cant-push-to-forked-repository-on-the-original-repositorys-pull-request-with-github-token/16287/2#M2372 that CI can't commit back to a fork, so I guess I'll drop that bit and just leave the change to output the diff.

**Comment by hadess** [comment]
> a) the CI job printed a diff showing what changes you should apply; or

A diff would have been fine. The CI job with a fixup commit wouldn't know how to fix up PRs with multiple commits (unless it ran the job on each commit individually, but then you'll likely run into conflicts).

**Review by gasinvein — APPROVED** [review]
LGTM

**Pull request merged**
