### PR TITLE
Add table of contents

### PR DESCRIPTION
**Pull request by TheEvilSkeleton**

### CODE REVIEW

**Comment by gasinvein** [comment]
Honestly I was thinking of moving documentation altogether to github wiki and removing it from the overgrown readme. @wjt @barthalion opinions?

**Comment by wjt** [comment]
No objection to moving it away from the README. another option could be sphinx documentation in/alongside the code and a job to publish it to GH pages / read the docs. Do-ocracy rules though!

**Comment by TheEvilSkeleton** [comment]
How can one contribute to the wiki? I've never really used the wiki to be honest.

**Comment by gasinvein** [comment]
I guess it's editable by anyone by default?

**Comment by TheEvilSkeleton** [comment]
I just checked. I can't edit it; I guess I need permissions.

Although it does tell you how to clone the wiki:
image

I just don't know how to contribute to it without needing any permissions. I just checked online and I don't think it has been implemented yet.

**Comment by gasinvein** [comment]
Looks like the is only "all or nothing" wiki permission setting - either everyone or only collaborators.
Anyway, I think it makes sense to merge it until we migrate docs to wiki.

**Pull request merged**
