### PR TITLE
Migrate tests to httpbingo.org

### PR DESCRIPTION
**Pull request by gasinvein**
httpbin seems abandoned, see postmanlabs/httpbin#617

### CODE REVIEW

**Comment by gasinvein** [comment]
Now `black --check` fails on old files. @wjt should we allow it to reformat?

**Comment by wjt** [comment]
Yeah, I think so – strange, I wonder what's changed, Black or the code?

**Comment by gasinvein** [comment]
I didn't change anything here but httpbin domain, so it must be black.

**Comment by wjt** [comment]
Thanks!

**Pull request merged**
